"""allow_null_model_name_and_comments

Revision ID: 44220055549a
Revises: 1519fd16159d
Create Date: 2025-04-25 11:11:37.565586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44220055549a'
down_revision: Union[str, None] = '1519fd16159d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建新表
    op.create_table(
        'evaluations_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('paper_id', sa.Integer(), nullable=False),
        sa.Column('score', sa.Float(), nullable=False),
        sa.Column('comments', sa.Text(), nullable=True),
        sa.Column('model_name', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 复制数据
    conn = op.get_bind()
    conn.execute(
        sa.text(
            """INSERT INTO evaluations_new 
               SELECT id, paper_id, score, comments, model_name, created_at 
               FROM evaluations"""
        )
    )
    
    # 删除旧表
    op.drop_table('evaluations')
    
    # 重命名新表
    op.rename_table('evaluations_new', 'evaluations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建新表（带有非空约束）
    op.create_table(
        'evaluations_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('paper_id', sa.Integer(), nullable=False),
        sa.Column('score', sa.Float(), nullable=False),
        sa.Column('comments', sa.Text(), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 复制数据
    conn = op.get_bind()
    conn.execute(
        sa.text(
            """INSERT INTO evaluations_new 
               SELECT id, paper_id, score, COALESCE(comments, ''), COALESCE(model_name, ''), created_at 
               FROM evaluations"""
        )
    )
    
    # 删除旧表
    op.drop_table('evaluations')
    
    # 重命名新表
    op.rename_table('evaluations_new', 'evaluations')
    # ### end Alembic commands ###
