"""recreate_knowledge_base_table

Revision ID: 920fff5f7fe8
Revises: 1dc3b0f16b7f
Create Date: 2025-04-25 11:48:24.135389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920fff5f7fe8'
down_revision: Union[str, None] = '1dc3b0f16b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查表是否存在
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'knowledge_base' not in tables:
        op.create_table('knowledge_base',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('title', sa.VARCHAR(length=255), nullable=False),
        sa.Column('file_path', sa.VARCHAR(length=255), nullable=False),
        sa.Column('language', sa.VARCHAR(length=50), nullable=True),
        sa.Column('vector', sa.TEXT(), nullable=True),
        sa.Column('created_at', sa.DATETIME(), nullable=True),
        sa.Column('updated_at', sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_knowledge_base_id', 'knowledge_base', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_base_id', table_name='knowledge_base')
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
