"""recreate knowledge base table

Revision ID: ab43b3ced6fd
Revises: 3c552e20dc35
Create Date: 2025-04-25 13:34:15.552657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab43b3ced6fd'
down_revision: Union[str, None] = '3c552e20dc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_base_id', table_name='knowledge_base')
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('language', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vector', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_base_id', 'knowledge_base', ['id'], unique=False)
    # ### end Alembic commands ###
